# General Settings
title: Micael Reis
email: micaelpreis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a personal website of a Software Engineer
url: "micaelreis.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Author Settings
author:
  name: "Micael Reis"
  profession: "Software Engineer"
  mail: mailto:micaelpreis@gmail.com
  twitter: https://twitter.com/micaelpreis
  github: https://github.com/micaelpreis
  linkedin: https://www.linkedin.com/in/micaelpreis/en

# Build Settings
source: ./
destination: ./_site
markdown: kramdown
highlighter: rouge

# Gems
gems:
  - jekyll-paginate

# Files To Exclude
exclude: ["Gemfile", "Gemfile.lock", "Readme.md", ]
